from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from app.auth.dependencies import get_disabled_auth_context

FUTURE_AUTH_CUTOVER_BLOCKERS = [
    "provider_selection",
    "real_credentials",
    "secret_management",
    "auth_implementation",
    "rbac_implementation",
    "route_guarding",
    "audit_actor_idempotency",
    "manual_review_action_workflow",
    "water_emergency_owner_review",
    "review_gui_chatgpt_review",
]

FUTURE_AUTH_CUTOVER_PREREQUISITES = [
    {
        "key": "provider_selected_by_randall",
        "label": "Provider selected by Randall",
        "status": "blocked_by_provider_selection",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Future auth cannot start until Randall selects the provider.",
    },
    {
        "key": "real_credentials_supplied_outside_git",
        "label": "Real credentials supplied outside Git",
        "status": "blocked_by_real_credentials",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Real credentials must be supplied through secure runtime configuration.",
    },
    {
        "key": "production_secret_storage_configured",
        "label": "Production secret storage configured",
        "status": "blocked_by_secret_management",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Production secrets must stay outside source control and example files.",
    },
    {
        "key": "token_verification_implementation_approved",
        "label": "Token verification implementation approved",
        "status": "blocked_by_auth_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Token verification remains a future reviewed implementation module.",
    },
    {
        "key": "jwks_network_fetching_policy_approved",
        "label": "JWKS/network fetching policy approved",
        "status": "blocked_by_auth_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Phase 0 does not fetch JWKS or contact identity providers.",
    },
    {
        "key": "frontend_login_logout_ux_approved",
        "label": "Frontend login/logout UX approved",
        "status": "blocked_by_auth_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Sign-in, sign-out, sessions, and token storage remain future work.",
    },
    {
        "key": "operator_identity_persistence_approved",
        "label": "Operator identity persistence approved",
        "status": "planned_future",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Operator identity is currently planning metadata only.",
    },
    {
        "key": "role_assignment_model_approved",
        "label": "Role assignment model approved",
        "status": "blocked_by_rbac_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Roles are future-planning labels and do not grant authority.",
    },
    {
        "key": "permission_enforcement_model_approved",
        "label": "Permission enforcement model approved",
        "status": "blocked_by_rbac_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Permissions are future-planning labels and are not enforced.",
    },
    {
        "key": "claims_mapping_finalized",
        "label": "Claims mapping finalized",
        "status": "blocked_by_auth_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Claims mapping is documented for future implementation only.",
    },
    {
        "key": "route_protection_matrix_approved_for_enforcement",
        "label": "Route protection matrix approved for enforcement",
        "status": "blocked_by_route_guarding",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Route protection is visible as planning metadata only.",
    },
    {
        "key": "manual_review_action_permission_model_approved",
        "label": "Manual Review action permission model approved",
        "status": "blocked_by_action_workflow",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Manual Review remains read-only until future action modules are approved.",
    },
    {
        "key": "water_emergency_action_permission_model_approved",
        "label": "Water Emergency action permission model approved",
        "status": "blocked_by_owner_review",
        "satisfied_now": False,
        "owner_review_required": True,
        "reason": (
            "Water Emergency action authority may affect legal, insurance, "
            "warranty, billing, or company-liability boundaries."
        ),
    },
    {
        "key": "audit_actor_integration_approved",
        "label": "Audit actor integration approved",
        "status": "blocked_by_audit",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Future actions need durable actor attribution before execution.",
    },
    {
        "key": "idempotency_integration_approved",
        "label": "Idempotency integration approved",
        "status": "blocked_by_audit",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Future mutation modules require idempotency before action execution.",
    },
    {
        "key": "immutable_event_writing_approved",
        "label": "Immutable event writing approved",
        "status": "blocked_by_audit",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Future executable actions must write immutable event evidence.",
    },
    {
        "key": "post_action_consistency_checks_approved",
        "label": "Post-action consistency checks approved",
        "status": "blocked_by_action_workflow",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Future action modules need post-action consistency checks.",
    },
    {
        "key": "rollback_replay_strategy_updated",
        "label": "Rollback/replay strategy updated",
        "status": "planned_future",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Rollback and replay planning remains non-executing Phase 0 context.",
    },
    {
        "key": "auth_staging_smoke_testing_plan_approved",
        "label": "Auth staging/smoke testing plan approved",
        "status": "blocked_by_auth_implementation",
        "satisfied_now": False,
        "owner_review_required": False,
        "reason": "Real auth cutover requires a future staging and smoke-test plan.",
    },
    {
        "key": "acssdr_stakeholder_report_update_mandatory",
        "label": "ACSSDR stakeholder report update remains mandatory",
        "status": "satisfied_now",
        "satisfied_now": True,
        "owner_review_required": False,
        "reason": "The previous-module ACSSDR update gate is part of the module workflow.",
    },
    {
        "key": "review_gui_chatgpt_review_mandatory",
        "label": "Review GUI + ChatGPT review remains mandatory",
        "status": "satisfied_now",
        "satisfied_now": True,
        "owner_review_required": False,
        "reason": "Commit approval remains outside Codex and requires review first.",
    },
]

CURRENT_ROUTE_ACCESSIBILITY_AUDIT = [
    {
        "method": "GET",
        "route": "/api/v1/health",
        "currently_requires_auth": False,
        "future_auth_required": False,
        "future_permission": "public.health.read",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Health remains a public read-only service readiness check.",
    },
    {
        "method": "GET",
        "route": "/api/v1/auth/status",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "auth.status.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Auth status is read-only Phase 0 visibility and is not a login endpoint.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/overview",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "dashboard.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Dashboard overview remains public read-only in Phase 0.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/lifecycle",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "dashboard.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Lifecycle visibility remains public read-only in Phase 0.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/review",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "manual_review.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Manual Review summary remains read-only and non-executing.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/manual-review/queue",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "manual_review.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Manual Review queue remains the visible safety queue, not an action surface.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/manual-review/queue/{review_item_id}",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "manual_review.detail.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Manual Review detail remains read-only investigation visibility.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/dispatch",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "dispatch.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Dispatch visibility remains read-only and does not execute dispatch.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/water-emergency",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "water_emergency.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Water Emergency dashboard remains separated read-only visibility.",
    },
    {
        "method": "GET",
        "route": "/api/v1/dashboard/water-emergency/{water_emergency_id}",
        "currently_requires_auth": False,
        "future_auth_required": True,
        "future_permission": "water_emergency.detail.view",
        "enforcement_enabled": False,
        "authorization_header_can_grant_authority": False,
        "reason": "Water Emergency detail remains separated read-only visibility.",
    },
]


def build_phase0_auth_status() -> dict[str, Any]:
    auth_context = get_disabled_auth_context()

    return {
        "generated_at": datetime.now(UTC),
        "phase0_auth_boundary_complete": True,
        "auth_implemented": False,
        "auth_enabled": auth_context.auth_enabled,
        "auth_provider": auth_context.auth_provider.value,
        "auth_mode": auth_context.auth_mode.value,
        "token_verification_enabled": False,
        "real_token_parsing_enabled": False,
        "disabled_token_verifier_available": True,
        "backend_auth_core_available": True,
        "frontend_disabled_session_available": True,
        "auth_status_bridge_available": True,
        "auth_status_endpoint_available": True,
        "rbac_enforcement_enabled": auth_context.rbac_enforced,
        "rbac_enforced": False,
        "route_protection_enforced": False,
        "route_guarding_enabled": False,
        "current_routes_require_auth": False,
        "authorization_header_required": False,
        "authorization_header_parsed": False,
        "authorization_header_can_grant_authority": False,
        "frontend_authorization_headers_emitted": False,
        "jwks_fetch_enabled": False,
        "login_ui_available": False,
        "user_management_available": False,
        "manual_review_action_authority_granted": (
            auth_context.manual_review_action_authority_granted
        ),
        "water_emergency_action_authority_granted": (
            auth_context.water_emergency_action_authority_granted
        ),
        "action_execution_available": False,
        "mutation_endpoints_available": False,
        "secret_hygiene_helper_available": True,
        "committed_credentials_allowed": False,
        "real_credentials_required_for_future_auth": True,
        "future_auth_cutover_ready": False,
        "future_auth_cutover_blocked_by": FUTURE_AUTH_CUTOVER_BLOCKERS,
        "future_auth_cutover_prerequisites": FUTURE_AUTH_CUTOVER_PREREQUISITES,
        "current_route_accessibility_audit": CURRENT_ROUTE_ACCESSIBILITY_AUDIT,
        "phase_allows_auth_enforcement": auth_context.phase_allows_enforcement,
        "phase_allows_rbac_enforcement": False,
        "phase_allows_route_guarding": False,
        "reason": (
            "Phase 0 auth status is a read-only bridge between the disabled "
            "backend auth scaffold and disabled frontend auth boundary. It does "
            "not parse Authorization headers, verify tokens, enforce RBAC, guard "
            "routes, or grant Manual Review or Water Emergency action authority."
        ),
    }
